### ISSUE TITLE
Maybe a bug handling big integers cooperating with neo-vm

### ISSUE THREAD

**Issue by Hecate2** [neo-project/neo-node#783]
I was attempting to call `addPair` in the contract https://github.com/Hecate2/neo-ruler/blob/master/ruler.py , using neo-cli. I typed the following command:
```
invoke 0x709dcde755e9152fa3b6b7f9e9d116f8eecdbc1b addPair [{"type":"Hash160","value":"0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5"},{"type":"Hash160","value":"0xd2a4cff31913016155e38e474a2c06d08be276cf"},{"type":"Integer","value":"1624723199999"},{"type":"String","value":"06_26_2021"},{"type":"Integer","value":"7"},{"type":"String","value":"7"},{"type":"Integer","value":"0"}]
```
where a very large integer of time stamp `1624723199999` (larger than 2147483647==2^31 -1) leads to the error:
```
Invoking script with: 'EAwBNxcMCjA2XzI2XzIwMjED/5cMSXoBAAAMFM924ovQBixKR47jVWEBExnzz6TSDBT1Y+pAvCg9TQ4FxI6jBbPyoHNA7xfAHwwHYWRkUGFpcgwUG7zN7vgW0en5t7ajLxXpVefNnXBBYn1bUg=='
VM State: FAULT
Gas Consumed: 10.1174359
Result Stack: []
Error: **Index was outside the bounds of the array.**
```
If the time stamp is changed to a very small positive value,
```
invoke 0x709dcde755e9152fa3b6b7f9e9d116f8eecdbc1b addPair [{"type":"Hash160","value":"0xef4073a0f2b305a38ec4050e4d3d28bc40ea63f5"},{"type":"Hash160","value":"0xd2a4cff31913016155e38e474a2c06d08be276cf"},{"type":"Integer","value":"162"},{"type":"String","value":"06_26_2021"},{"type":"Integer","value":"7"},{"type":"String","value":"7"},{"type":"Integer","value":"0"}]
```
no C#-level exception would occur (although the engine goes FAULT because I asserted in my contract that current time is smaller than the time stamp)
```
Invoking script with: 'EAwBNxcMCjA2XzI2XzIwMjEBogAMFM924ovQBixKR47jVWEBExnzz6TSDBT1Y+pAvCg9TQ4FxI6jBbPyoHNA7xfAHwwHYWRkUGFpcgwUG7zN7vgW0en5t7ajLxXpVefNnXBBYn1bUg=='
VM State: FAULT
Gas Consumed: 0.0635853
Result Stack: []
Error: ASSERT is executed with false result.
```
However, I am able to invoke `addPair` using very big time stamps with the Python SDK `neo-mamba` (using https://github.com/Hecate2/neo-ruler/blob/master/ruler_test.py) (though I cannot assign the CallingScriptHash and thus I cannot deposit any NEO into the contract). I guess the reason as the followings:

In neo-cli and neo-vm, we invoke the contract as follows:
https://github.com/neo-project/neo-node/blob/32e3ed6a1a06e2477b29e8881a771e021ef36a18/neo-cli/CLI/MainService.cs#L599
(where `parameters.ToArray()` is called)

https://github.com/neo-project/neo/blob/7e2d435aada96e7e22c7564984bff1419377c33f/src/neo/VM/Helper.cs#L97
(where the args are dumped as an array)

https://github.com/neo-project/neo/blob/7e2d435aada96e7e22c7564984bff1419377c33f/src/neo/VM/Helper.cs#L28
(where indexing is used to push args in the array into the stack)

In the function `public static ScriptBuilder CreateArray` quoted above, we have:
```c#
for (int i = list.Count - 1; i >= 0; i--)
    builder.EmitPush(list[i]);
```

However, in `neo-mamba`, we have:
https://github.com/CityOfZion/neo-mamba/blob/873932c8cb25497b90a39b3e327572746764e699/neo3/vm/__init__.py#L25
```python
        for arg in reversed(args):
            self.emit_push(arg)
```
and no expressions similar to `ToArray()` is used in Python.

**Comment by erikzhang** [comment]
Can you try it with the latest neo-vm? I think it should be fixed by https://github.com/neo-project/neo-vm/pull/413

**Comment by Hecate2** [comment]
> Can you try it with the latest neo-vm? I think it should be fixed by [neo-project/neo-vm#413](https://github.com/neo-project/neo-vm/pull/413)

It seems the latest fix does not resolve the problem. In `neo-mamba` I use an old vm and nothing goes wrong. And the new tests introduced by [neo-project/neo-vm#413](https://github.com/neo-project/neo-vm/pull/413) did not mention scenarios of very big integers input from neo-cli. (But I believe very big integers can be handled correctly by the vm)

**Comment by cloud8little** [comment]
> > Can you try it with the latest neo-vm? I think it should be fixed by [neo-project/neo-vm#413](https://github.com/neo-project/neo-vm/pull/413)
> 
> It seems the latest fix does not resolve the problem. In `neo-mamba` I use an old vm and nothing goes wrong. And the new tests introduced by [neo-project/neo-vm#413](https://github.com/neo-project/neo-vm/pull/413) did not mention scenarios of very big integers input from neo-cli. (But I believe very big integers can be handled correctly by the vm)

the root cause is you try to deploy a contract dynamically without passing a signer.

**Comment by Hecate2** [comment]
> the root cause is you try to deploy a contract dynamically without passing a signer.
I see. It was my fault that I did not give a correct sender
